---
dist: trusty
language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo test --features="par_iter"
  - cargo test --no-default-features
notifications:
  email:
    on_success: never
